---
 - name: Configure local repository
   template: src=local.repo.j2 dest=/etc/yum.repos.d/local.repo owner=root group=root mode=644
   become: yes
   
 - name: Install epel repo
   yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm state=present
   when: ansible_os_family == "RedHat"
   become: yes

 - name: Install basic packets
   yum: name={{ item }} state=present
   become: yes
   with_items:
    - python-pip
    - gcc
   

